import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Outcash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="//code.jivosite.com/widget/5KoL49mcZ7" async></script>
      </Head>
    <Header/>
    <main>
    <div id='content'>
    <h2 className='text'>O OutCash, é a sua solução para suas dúvidas sobre o mundo financeiro.
    Somos uma plataforma simples com o objetivo de trazer suas finanças de volta para seu controle.</h2>
    <button id='Hbutton'>
      <a href="http://" target="_blank" rel="noopener noreferrer">Acesse a plataforma</a>
    </button>
  </div>
  <ul id='Homelist'> 
    <li className='listch'>
       <Image
      src='/money.png'
      width={100}
      height={100}
  />  Educação finacneira
    </li>
    <li className='listch'>
      <Image
      src= '/sup.png'
      width={100}
      height={100}
      />
      Suporte de especialista
    </li>

    <li className='listch'>
      <Image
      src='/graphic.png'
      width={100}
      height={100}
      
      />Dados em tempo real

    </li>
  
  
  </ul>
 
  </main>
    </div>
  )
}
